services:
#    nfl.example:
#        class: NflBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

  nfl.lib.n2goprovider:
    class: NflBundle\Lib\N2GoProvider
    calls:
        - [setContainer, ["@service_container"]]

  nfl.lib.ratinghandler:
    class: NflBundle\Lib\RatingHandler
    calls:
        - [setContainer, ["@service_container"]]

  nfl.lib.nflhandler:
    class: NflBundle\Lib\NflHandler
    arguments:
        - @nfl.lib.n2goprovider
        - @nfl.lib.ratinghandler
        - @templating
        - @event_dispatcher
    calls:
        - [setContainer, ["@service_container"]]

  nfl.command.urls:
      class: NflBundle\Command\UrlsCommand
      arguments:
          - @nfl.lib.nflhandler
      tags:
          -  { name: console.command }

  nfl.command.schedule:
      class: NflBundle\Command\ScheduleCommand
      arguments:
          - @nfl.lib.nflhandler
      tags:
          -  { name: console.command }

  nfl.command.stream:
      class: NflBundle\Command\StreamCommand
      arguments:
          - @nfl.lib.nflhandler
      tags:
          -  { name: console.command }

  nfl.command.rating:
      class: NflBundle\Command\RatingCommand
      arguments:
          - @nfl.lib.nflhandler
      tags:
          -  { name: console.command }

  nfl.command.cron:
      class: NflBundle\Command\CronCommand
      arguments:
          - @nfl.lib.nflhandler
      tags:
          -  { name: console.command }